

#ifndef GROUP_AUGMENTATION_ATTRIBUTE_H
#define GROUP_AUGMENTATION_ATTRIBUTE_H

enum Attribute {
    ALPHA, ALPHA_AGE, BETA, BETA_RANK, GAMMA, GAMMA_RANK, DRIFT, DISPERSAL, HELP, HELP_TYPE, TASK, SURVIVAL, AGE, RANK, AGE_BECOME_BREEDER, RANK_BECOME_BREEDER

};

#endif //GROUP_AUGMENTATION_ATTRIBUTE_H
