

#ifndef GROUP_AUGMENTATION_ATTRIBUTE_H
#define GROUP_AUGMENTATION_ATTRIBUTE_H

enum Attribute {
    ALPHA, ALPHA_AGE, BETA, BETA_AGE, GAMMA, GAMMA_AGE, DRIFT, DISPERSAL, HELP, TASK, SURVIVAL, AGE, RANK
};

#endif //GROUP_AUGMENTATION_ATTRIBUTE_H
